// <auto-generated />
namespace Entities.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class add_Dob_customer : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_Dob_customer));
        
        string IMigrationMetadata.Id
        {
            get { return "202001020730184_add_Dob_customer"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
