// <auto-generated />
namespace Entities.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class add_createDate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_createDate));
        
        string IMigrationMetadata.Id
        {
            get { return "202001040406596_add_createDate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
